# Generated by Django 3.0.5 on 2022-05-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_topping_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='text',
        ),
    ]
