# Generated by Django 3.0.5 on 2022-05-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='owner',
        ),
        migrations.AddField(
            model_name='comments',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza'),
            preserve_default=False,
        ),
    ]
