# Generated by Django 3.0.5 on 2022-05-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20220506_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_pics',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
